export const projects = [
    {
      title: 'CryptoHub',
      description: "This is a web quiz app that was built with react and redux was used for state management. In this video, we will create a full Realtime Chat Application.",
        image: '/images/1.png',
        tags: ['React', 'RTK Query', 'Ant Design', 'Chart-js'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 0,
    },
    {
      title: 'Portfolio-App',
      description:"This is a web quiz app that was built with react and redux was used for state management. In this video, we will create a full Realtime Chat Application.",
      image: '/images/2.png',
      tags: ['React', 'Styled Components', 'React-Scroll'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 1,
    },
    {
      title: 'Budget App',
      description: "This is a web quiz app that was built with react and redux was used for state management. In this video, we will create a full Realtime Chat Application.",
        image: '/images/3.png',
        tags: ['React', 'Context Api', 'MUI', 'Chart-js'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 2,
    },
    {
      title: 'Unichat',
      description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
      image: '/images/4.jpg',
      tags: ['React', 'ChatEngine', 'Firebase'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
    {
      title: 'Quiz-App',
      description: "This is a web quiz app that was built with react and redux was used for state management. In this video, we will create a full Realtime Chat Application",
      image: '/images/5.png',
      tags: ['React', 'Redux', 'MUI', 'API'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 4,
    },
    {
      title: 'TechJobs',
      description: "This is a web quiz app that was built with react and redux was used for state management. In this video, we will create a full Realtime Chat Application",
      image: '/images/6.png',
      tags: ['React', 'Javascript', 'Styled Components'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 5
    }
  ];